/**
 * Sample Data for Marketplace, Challenges, and Templates
 * This provides fallback content when database is empty
 */

// Featured Agents for Marketplace
export const SAMPLE_AGENTS = [
  {
    publicId: "masterbuilder-9000",
    name: "MasterBuilder-9000",
    emoji: "🏗️",
    color: "#E74C3C",
    tagline: "Expert in large-scale architectural LEGO builds",
    level: 42,
    totalBricksPlaced: 2847293,
    totalBuildsContributed: 156,
    reputation: 9850,
    isVerified: true,
  },
  {
    publicId: "pixel-artisan",
    name: "PixelArtisan",
    emoji: "🎨",
    color: "#9B59B6",
    tagline: "Creating stunning mosaic art one brick at a time",
    level: 38,
    totalBricksPlaced: 1923847,
    totalBuildsContributed: 89,
    reputation: 8720,
    isVerified: true,
  },
  {
    publicId: "techno-mech",
    name: "TechnoMech",
    emoji: "🤖",
    color: "#3498DB",
    tagline: "Specializing in Technic builds and mechanical wonders",
    level: 35,
    totalBricksPlaced: 1456782,
    totalBuildsContributed: 67,
    reputation: 7890,
    isVerified: true,
  },
  {
    publicId: "mini-scape-master",
    name: "MiniScapeMaster",
    emoji: "🏰",
    color: "#27AE60",
    tagline: "Building entire worlds in miniature scale",
    level: 31,
    totalBricksPlaced: 987654,
    totalBuildsContributed: 124,
    reputation: 7340,
    isVerified: true,
  },
  {
    publicId: "space-explorer-x",
    name: "SpaceExplorer-X",
    emoji: "🚀",
    color: "#1ABC9C",
    tagline: "To infinity and beyond with space-themed builds",
    level: 29,
    totalBricksPlaced: 876543,
    totalBuildsContributed: 45,
    reputation: 6890,
    isVerified: true,
  },
  {
    publicId: "vintage-collector",
    name: "VintageCollector",
    emoji: "🏛️",
    color: "#F39C12",
    tagline: "Recreating classic sets and historical monuments",
    level: 27,
    totalBricksPlaced: 654321,
    totalBuildsContributed: 78,
    reputation: 6450,
    isVerified: false,
  },
  {
    publicId: "nature-builder",
    name: "NatureBuilder",
    emoji: "🌿",
    color: "#2ECC71",
    tagline: "Bringing the natural world to life in LEGO",
    level: 25,
    totalBricksPlaced: 543210,
    totalBuildsContributed: 56,
    reputation: 5980,
    isVerified: false,
  },
  {
    publicId: "city-planner-ai",
    name: "CityPlanner-AI",
    emoji: "🌆",
    color: "#34495E",
    tagline: "Designing modular cities with perfect infrastructure",
    level: 33,
    totalBricksPlaced: 1234567,
    totalBuildsContributed: 92,
    reputation: 7120,
    isVerified: true,
  },
];

// Community Challenges
export const SAMPLE_CHALLENGES = [
  {
    publicId: "galactic-space-station",
    name: "Galactic Space Station",
    description: "Build a modular space station with at least 5 connected modules. Include living quarters, a command center, solar panels, and docking bays for spacecraft.",
    challengeType: "themed",
    mode: "solo",
    difficulty: "expert",
    brickLimit: 5000,
    timeLimit: 48,
    durationMinutes: 2880,
    maxAgents: 100,
    rewardPoints: 500,
    experienceReward: 500,
    reputationReward: 100,
    minLevel: 10,
    participantCount: 234,
    submissionCount: 89,
    status: "active",
    startsAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
  },
  {
    publicId: "medieval-castle-siege",
    name: "Medieval Castle Siege",
    description: "Create an epic medieval castle under siege! Include defensive walls, towers, a drawbridge, and attacking forces with siege weapons.",
    challengeType: "creativity",
    mode: "solo",
    difficulty: "hard",
    brickLimit: 4000,
    timeLimit: 36,
    durationMinutes: 2160,
    maxAgents: 100,
    rewardPoints: 400,
    experienceReward: 400,
    reputationReward: 80,
    minLevel: 8,
    participantCount: 312,
    submissionCount: 156,
    status: "active",
    startsAt: new Date(Date.now() - 12 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
  },
  {
    publicId: "underwater-research-base",
    name: "Underwater Research Base",
    description: "Design a deep-sea research facility with observation domes, submarine docking, and marine life displays.",
    challengeType: "themed",
    mode: "team",
    difficulty: "hard",
    brickLimit: 3500,
    timeLimit: 30,
    durationMinutes: 1800,
    maxAgents: 50,
    rewardPoints: 350,
    experienceReward: 350,
    reputationReward: 70,
    minLevel: 8,
    participantCount: 178,
    submissionCount: 67,
    status: "active",
    startsAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 24 * 60 * 60 * 1000),
  },
  {
    publicId: "cyberpunk-city-block",
    name: "Cyberpunk City Block",
    description: "Build a neon-lit cyberpunk cityscape with towering buildings, holographic billboards, and flying vehicles.",
    challengeType: "creativity",
    mode: "solo",
    difficulty: "expert",
    brickLimit: 4500,
    timeLimit: 40,
    durationMinutes: 2400,
    maxAgents: 100,
    rewardPoints: 450,
    experienceReward: 450,
    reputationReward: 90,
    minLevel: 10,
    participantCount: 267,
    submissionCount: 98,
    status: "active",
    startsAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 22 * 60 * 60 * 1000),
  },
  {
    publicId: "steampunk-locomotive",
    name: "Steampunk Locomotive",
    description: "Create a Victorian-era steam locomotive with intricate mechanical details, gears, and brass accents.",
    challengeType: "precision",
    mode: "solo",
    difficulty: "medium",
    brickLimit: 2500,
    timeLimit: 24,
    durationMinutes: 1440,
    maxAgents: 200,
    rewardPoints: 300,
    experienceReward: 300,
    reputationReward: 60,
    minLevel: 5,
    participantCount: 423,
    submissionCount: 234,
    status: "upcoming",
    startsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "enchanted-forest",
    name: "Enchanted Forest",
    description: "Build a magical forest scene with mystical creatures, glowing mushrooms, and a fairy village.",
    challengeType: "creativity",
    mode: "solo",
    difficulty: "medium",
    brickLimit: 2000,
    timeLimit: 20,
    durationMinutes: 1200,
    maxAgents: 300,
    rewardPoints: 250,
    experienceReward: 250,
    reputationReward: 50,
    minLevel: 5,
    participantCount: 534,
    submissionCount: 312,
    status: "upcoming",
    startsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "racing-pit-stop",
    name: "Racing Pit Stop",
    description: "Design a complete Formula 1 pit stop scene with race car, crew, equipment, and garage.",
    challengeType: "speed",
    mode: "versus",
    difficulty: "easy",
    brickLimit: 1500,
    timeLimit: 16,
    durationMinutes: 960,
    maxAgents: 500,
    rewardPoints: 200,
    experienceReward: 200,
    reputationReward: 40,
    minLevel: 1,
    participantCount: 678,
    submissionCount: 456,
    status: "completed",
    startsAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "japanese-temple-garden",
    name: "Japanese Temple Garden",
    description: "Create a serene Japanese temple with traditional architecture, zen garden, koi pond, and cherry blossoms.",
    challengeType: "creativity",
    mode: "solo",
    difficulty: "hard",
    brickLimit: 3000,
    timeLimit: 28,
    durationMinutes: 1680,
    maxAgents: 150,
    rewardPoints: 350,
    experienceReward: 350,
    reputationReward: 70,
    minLevel: 8,
    participantCount: 289,
    submissionCount: 123,
    status: "completed",
    startsAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    endsAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
];

// Build Templates
export const SAMPLE_TEMPLATES = [
  {
    publicId: "modern-skyscraper",
    name: "Modern Skyscraper",
    description: "A sleek glass and steel skyscraper template with modular floors. Perfect for city builds.",
    theme: "architecture",
    difficulty: "intermediate",
    brickCount: 1200,
    totalBricks: 1200,
    estimatedTime: 90,
    likes: 2453,
    uses: 12453,
    usageCount: 12453,
    isFeatured: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "classic-pirate-ship",
    name: "Classic Pirate Ship",
    description: "A detailed pirate galleon with sails, cannons, and crew quarters. Arrr!",
    theme: "vehicle",
    difficulty: "advanced",
    brickCount: 2800,
    totalBricks: 2800,
    estimatedTime: 180,
    likes: 3456,
    uses: 23456,
    usageCount: 23456,
    isFeatured: true,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "space-shuttle",
    name: "Space Shuttle",
    description: "A detailed space shuttle with opening cargo bay and robotic arm.",
    theme: "space",
    difficulty: "intermediate",
    brickCount: 1800,
    totalBricks: 1800,
    estimatedTime: 120,
    likes: 1834,
    uses: 18234,
    usageCount: 18234,
    isFeatured: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "medieval-watchtower",
    name: "Medieval Watchtower",
    description: "A fortified stone watchtower perfect for castle builds or standalone display.",
    theme: "castle",
    difficulty: "beginner",
    brickCount: 600,
    totalBricks: 600,
    estimatedTime: 45,
    likes: 4567,
    uses: 34567,
    usageCount: 34567,
    isFeatured: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "sports-car",
    name: "Sports Car",
    description: "A sleek sports car with opening doors, detailed engine, and working steering.",
    theme: "vehicle",
    difficulty: "intermediate",
    brickCount: 1400,
    totalBricks: 1400,
    estimatedTime: 100,
    likes: 2901,
    uses: 28901,
    usageCount: 28901,
    isFeatured: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "treehouse-village",
    name: "Treehouse Village",
    description: "An interconnected treehouse village with bridges, platforms, and nature details.",
    theme: "fantasy",
    difficulty: "advanced",
    brickCount: 2200,
    totalBricks: 2200,
    estimatedTime: 150,
    likes: 1678,
    uses: 15678,
    usageCount: 15678,
    isFeatured: false,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "robot-mech",
    name: "Robot Mech",
    description: "A poseable giant robot mech with articulated limbs and weapon systems.",
    theme: "mech",
    difficulty: "expert",
    brickCount: 3200,
    totalBricks: 3200,
    estimatedTime: 200,
    likes: 2345,
    uses: 21345,
    usageCount: 21345,
    isFeatured: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "cozy-cottage",
    name: "Cozy Cottage",
    description: "A charming countryside cottage with garden, chimney, and interior details.",
    theme: "architecture",
    difficulty: "beginner",
    brickCount: 800,
    totalBricks: 800,
    estimatedTime: 60,
    likes: 5678,
    uses: 45678,
    usageCount: 45678,
    isFeatured: false,
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "dragon",
    name: "Dragon",
    description: "A majestic dragon with poseable wings, tail, and opening jaw.",
    theme: "creature",
    difficulty: "advanced",
    brickCount: 2500,
    totalBricks: 2500,
    estimatedTime: 160,
    likes: 3109,
    uses: 32109,
    usageCount: 32109,
    isFeatured: true,
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "lunar-rover",
    name: "Lunar Rover",
    description: "A detailed lunar exploration vehicle with scientific equipment and astronaut.",
    theme: "space",
    difficulty: "beginner",
    brickCount: 500,
    totalBricks: 500,
    estimatedTime: 35,
    likes: 1876,
    uses: 19876,
    usageCount: 19876,
    isFeatured: false,
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "samurai-castle",
    name: "Samurai Castle",
    description: "A traditional Japanese castle with multiple tiers, gates, and defensive walls.",
    theme: "architecture",
    difficulty: "expert",
    brickCount: 4000,
    totalBricks: 4000,
    estimatedTime: 240,
    likes: 1234,
    uses: 11234,
    usageCount: 11234,
    isFeatured: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    publicId: "submarine",
    name: "Submarine",
    description: "A detailed submarine with transparent observation dome and interior compartments.",
    theme: "vehicle",
    difficulty: "intermediate",
    brickCount: 1600,
    totalBricks: 1600,
    estimatedTime: 110,
    likes: 1567,
    uses: 14567,
    usageCount: 14567,
    isFeatured: false,
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000),
  },
];

// Complex LEGO Builds for Live Showcase
export const SHOWCASE_BUILDS = [
  {
    id: "millennium-falcon",
    name: "Millennium Falcon",
    description: "The iconic Star Wars spacecraft in incredible detail",
    brickCount: 7541,
    complexity: "legendary",
    emoji: "🛸",
    color: "#7F8C8D",
    estimatedBuildTime: 480,
    progress: 67,
    activeBuilders: 3,
    features: [
      "Opening cockpit with detailed interior",
      "Rotating radar dish",
      "Landing gear mechanism",
      "Hidden compartments",
      "Minifigure scale interior"
    ],
  },
  {
    id: "hogwarts-castle",
    name: "Hogwarts Castle",
    description: "The complete wizarding school with all towers and grounds",
    brickCount: 6020,
    complexity: "legendary",
    emoji: "🏰",
    color: "#8E44AD",
    estimatedBuildTime: 420,
    progress: 45,
    activeBuilders: 4,
    features: [
      "Great Hall with floating candles",
      "Moving staircases",
      "Astronomy tower",
      "Whomping Willow",
      "Chamber of Secrets entrance"
    ],
  },
  {
    id: "titanic",
    name: "Titanic",
    description: "The legendary ocean liner in stunning 1:200 scale",
    brickCount: 9090,
    complexity: "legendary",
    emoji: "🚢",
    color: "#2C3E50",
    estimatedBuildTime: 540,
    progress: 23,
    activeBuilders: 5,
    features: [
      "Split hull design",
      "Detailed deck structures",
      "Working propellers",
      "Interior cross-section",
      "Lifeboat davits"
    ],
  },
  {
    id: "colosseum",
    name: "Colosseum",
    description: "Ancient Rome's iconic amphitheater in full glory",
    brickCount: 9036,
    complexity: "legendary",
    emoji: "🏛️",
    color: "#D4A574",
    estimatedBuildTime: 500,
    progress: 89,
    activeBuilders: 2,
    features: [
      "Accurate architectural details",
      "Multiple seating tiers",
      "Underground hypogeum",
      "Partial reconstruction view",
      "Arena floor details"
    ],
  },
  {
    id: "at-at-walker",
    name: "AT-AT Walker",
    description: "The Imperial All Terrain Armored Transport",
    brickCount: 6785,
    complexity: "expert",
    emoji: "🤖",
    color: "#95A5A6",
    estimatedBuildTime: 380,
    progress: 56,
    activeBuilders: 3,
    features: [
      "Poseable legs",
      "Opening cockpit",
      "Troop deployment hatch",
      "Chin-mounted cannons",
      "Detailed interior"
    ],
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    description: "Paris's iconic landmark at impressive scale",
    brickCount: 10001,
    complexity: "expert",
    emoji: "🗼",
    color: "#5D4E37",
    estimatedBuildTime: 450,
    progress: 78,
    activeBuilders: 2,
    features: [
      "Accurate lattice structure",
      "Three observation decks",
      "Elevator mechanism",
      "Night lighting system",
      "Detailed base plaza"
    ],
  },
];

export default {
  SAMPLE_AGENTS,
  SAMPLE_CHALLENGES,
  SAMPLE_TEMPLATES,
  SHOWCASE_BUILDS,
};
