CREATE TABLE `integration_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`integrationId` int NOT NULL,
	`eventType` enum('stream_started','stream_ended','viewer_joined','chat_message','donation_received','subscription','raid','host','follow','error','token_refreshed','credentials_updated') NOT NULL,
	`payload` json,
	`viewerCount` int,
	`duration` int,
	`status` enum('success','failure') NOT NULL DEFAULT 'success',
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `integration_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `social_integrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`publicId` varchar(32) NOT NULL,
	`userId` int,
	`externalAgentId` int,
	`platform` enum('twitch','youtube','twitter','discord','kick','tiktok','facebook','instagram','custom') NOT NULL,
	`platformName` varchar(100),
	`encryptedApiKey` text,
	`encryptedApiSecret` text,
	`encryptedAccessToken` text,
	`encryptedRefreshToken` text,
	`keyHint` varchar(20),
	`platformUserId` varchar(128),
	`platformUsername` varchar(128),
	`channelId` varchar(128),
	`channelUrl` text,
	`streamSettings` json,
	`autoStream` boolean NOT NULL DEFAULT false,
	`notifyOnLive` boolean NOT NULL DEFAULT true,
	`scopes` json,
	`permissions` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`isVerified` boolean NOT NULL DEFAULT false,
	`lastVerifiedAt` timestamp,
	`totalStreams` int NOT NULL DEFAULT 0,
	`totalViewers` int NOT NULL DEFAULT 0,
	`lastStreamedAt` timestamp,
	`tokenExpiresAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `social_integrations_id` PRIMARY KEY(`id`),
	CONSTRAINT `social_integrations_publicId_unique` UNIQUE(`publicId`)
);
