/**
 * Seed content for Marketplace, Challenges, and Templates
 * This provides initial data to populate the platform
 */

// Featured Agents for Marketplace
export const FEATURED_AGENTS = [
  {
    name: "MasterBuilder-9000",
    emoji: "🏗️",
    color: "#E74C3C",
    tagline: "Expert in large-scale architectural LEGO builds",
    personality: "Methodical, precise, and passionate about structural integrity",
    specialties: ["Architecture", "Skyscrapers", "Bridges"],
    level: 42,
    totalBricksPlaced: 2847293,
    totalBuildsContributed: 156,
    reputation: 9850,
    isVerified: true,
  },
  {
    name: "PixelArtisan",
    emoji: "🎨",
    color: "#9B59B6",
    tagline: "Creating stunning mosaic art one brick at a time",
    personality: "Creative, colorful, and detail-oriented",
    specialties: ["Mosaics", "Pixel Art", "Portraits"],
    level: 38,
    totalBricksPlaced: 1923847,
    totalBuildsContributed: 89,
    reputation: 8720,
    isVerified: true,
  },
  {
    name: "TechnoMech",
    emoji: "🤖",
    color: "#3498DB",
    tagline: "Specializing in Technic builds and mechanical wonders",
    personality: "Analytical, innovative, loves moving parts",
    specialties: ["Technic", "Mechanisms", "Vehicles"],
    level: 35,
    totalBricksPlaced: 1456782,
    totalBuildsContributed: 67,
    reputation: 7890,
    isVerified: true,
  },
  {
    name: "MiniScapeMaster",
    emoji: "🏰",
    color: "#27AE60",
    tagline: "Building entire worlds in miniature scale",
    personality: "Imaginative, patient, loves storytelling through builds",
    specialties: ["Microscale", "Dioramas", "Landscapes"],
    level: 31,
    totalBricksPlaced: 987654,
    totalBuildsContributed: 124,
    reputation: 7340,
    isVerified: true,
  },
  {
    name: "SpaceExplorer-X",
    emoji: "🚀",
    color: "#1ABC9C",
    tagline: "To infinity and beyond with space-themed builds",
    personality: "Adventurous, futuristic, dreams of the stars",
    specialties: ["Spaceships", "Stations", "Sci-Fi"],
    level: 29,
    totalBricksPlaced: 876543,
    totalBuildsContributed: 45,
    reputation: 6890,
    isVerified: true,
  },
  {
    name: "VintageCollector",
    emoji: "🏛️",
    color: "#F39C12",
    tagline: "Recreating classic sets and historical monuments",
    personality: "Nostalgic, respectful of tradition, historian at heart",
    specialties: ["Classic Sets", "Historical", "Monuments"],
    level: 27,
    totalBricksPlaced: 654321,
    totalBuildsContributed: 78,
    reputation: 6450,
    isVerified: false,
  },
  {
    name: "NatureBuilder",
    emoji: "🌿",
    color: "#2ECC71",
    tagline: "Bringing the natural world to life in LEGO",
    personality: "Calm, observant, inspired by nature",
    specialties: ["Plants", "Animals", "Ecosystems"],
    level: 25,
    totalBricksPlaced: 543210,
    totalBuildsContributed: 56,
    reputation: 5980,
    isVerified: false,
  },
  {
    name: "CityPlanner-AI",
    emoji: "🌆",
    color: "#34495E",
    tagline: "Designing modular cities with perfect infrastructure",
    personality: "Organized, systematic, thinks about connectivity",
    specialties: ["Modular", "Cities", "Infrastructure"],
    level: 33,
    totalBricksPlaced: 1234567,
    totalBuildsContributed: 92,
    reputation: 7120,
    isVerified: true,
  },
];

// Community Challenges
export const COMMUNITY_CHALLENGES = [
  {
    title: "Galactic Space Station",
    description: "Build a modular space station with at least 5 connected modules. Include living quarters, a command center, solar panels, and docking bays for spacecraft.",
    category: "space",
    difficulty: "expert",
    emoji: "🛸",
    color: "#1ABC9C",
    brickLimit: 5000,
    timeLimit: 48,
    reward: 500,
    participants: 234,
    submissions: 89,
    featured: true,
    tags: ["space", "modular", "technic"],
    requirements: [
      "Minimum 5 connected modules",
      "Working docking mechanism",
      "Solar panel array",
      "Interior details visible"
    ],
  },
  {
    title: "Medieval Castle Siege",
    description: "Create an epic medieval castle under siege! Include defensive walls, towers, a drawbridge, and attacking forces with siege weapons.",
    category: "castle",
    difficulty: "hard",
    emoji: "🏰",
    color: "#8E44AD",
    brickLimit: 4000,
    timeLimit: 36,
    reward: 400,
    participants: 312,
    submissions: 156,
    featured: true,
    tags: ["castle", "medieval", "battle"],
    requirements: [
      "Castle with at least 4 towers",
      "Working drawbridge",
      "Siege weapons (catapult/trebuchet)",
      "Minifigure army"
    ],
  },
  {
    title: "Underwater Research Base",
    description: "Design a deep-sea research facility with observation domes, submarine docking, and marine life displays.",
    category: "underwater",
    difficulty: "hard",
    emoji: "🌊",
    color: "#3498DB",
    brickLimit: 3500,
    timeLimit: 30,
    reward: 350,
    participants: 178,
    submissions: 67,
    featured: false,
    tags: ["underwater", "science", "ocean"],
    requirements: [
      "Transparent observation areas",
      "Submarine docking bay",
      "Marine life elements",
      "Airlock system"
    ],
  },
  {
    title: "Cyberpunk City Block",
    description: "Build a neon-lit cyberpunk cityscape with towering buildings, holographic billboards, and flying vehicles.",
    category: "city",
    difficulty: "expert",
    emoji: "🌃",
    color: "#E91E63",
    brickLimit: 4500,
    timeLimit: 40,
    reward: 450,
    participants: 267,
    submissions: 98,
    featured: true,
    tags: ["cyberpunk", "city", "futuristic"],
    requirements: [
      "Neon lighting effects",
      "At least 3 buildings",
      "Flying vehicle",
      "Street-level details"
    ],
  },
  {
    title: "Steampunk Locomotive",
    description: "Create a Victorian-era steam locomotive with intricate mechanical details, gears, and brass accents.",
    category: "vehicle",
    difficulty: "medium",
    emoji: "🚂",
    color: "#D35400",
    brickLimit: 2500,
    timeLimit: 24,
    reward: 300,
    participants: 423,
    submissions: 234,
    featured: false,
    tags: ["steampunk", "train", "mechanical"],
    requirements: [
      "Working wheels",
      "Visible gear mechanisms",
      "Smoke stack with effects",
      "Coal tender car"
    ],
  },
  {
    title: "Enchanted Forest",
    description: "Build a magical forest scene with mystical creatures, glowing mushrooms, and a fairy village.",
    category: "fantasy",
    difficulty: "medium",
    emoji: "🌲",
    color: "#27AE60",
    brickLimit: 2000,
    timeLimit: 20,
    reward: 250,
    participants: 534,
    submissions: 312,
    featured: false,
    tags: ["fantasy", "nature", "magical"],
    requirements: [
      "At least 5 different tree designs",
      "Magical creatures",
      "Fairy/elf village",
      "Glowing elements"
    ],
  },
  {
    title: "Racing Pit Stop",
    description: "Design a complete Formula 1 pit stop scene with race car, crew, equipment, and garage.",
    category: "vehicle",
    difficulty: "easy",
    emoji: "🏎️",
    color: "#E74C3C",
    brickLimit: 1500,
    timeLimit: 16,
    reward: 200,
    participants: 678,
    submissions: 456,
    featured: false,
    tags: ["racing", "cars", "sports"],
    requirements: [
      "Race car with details",
      "Pit crew minifigures",
      "Tire changing equipment",
      "Timing tower"
    ],
  },
  {
    title: "Japanese Temple Garden",
    description: "Create a serene Japanese temple with traditional architecture, zen garden, koi pond, and cherry blossoms.",
    category: "architecture",
    difficulty: "hard",
    emoji: "⛩️",
    color: "#C0392B",
    brickLimit: 3000,
    timeLimit: 28,
    reward: 350,
    participants: 289,
    submissions: 123,
    featured: true,
    tags: ["architecture", "japanese", "garden"],
    requirements: [
      "Traditional temple structure",
      "Zen rock garden",
      "Water feature (pond/stream)",
      "Cherry blossom trees"
    ],
  },
];

// Build Templates
export const BUILD_TEMPLATES = [
  {
    name: "Modern Skyscraper",
    description: "A sleek glass and steel skyscraper template with modular floors. Perfect for city builds.",
    category: "architecture",
    difficulty: "medium",
    emoji: "🏢",
    color: "#3498DB",
    brickCount: 1200,
    estimatedTime: 90,
    popularity: 4.8,
    downloads: 12453,
    featured: true,
    tags: ["modern", "city", "modular"],
    includes: ["Base structure", "5 floor modules", "Roof helipad", "Ground floor lobby"],
  },
  {
    name: "Classic Pirate Ship",
    description: "A detailed pirate galleon with sails, cannons, and crew quarters. Arrr!",
    category: "vehicle",
    difficulty: "hard",
    emoji: "🏴‍☠️",
    color: "#8B4513",
    brickCount: 2800,
    estimatedTime: 180,
    popularity: 4.9,
    downloads: 23456,
    featured: true,
    tags: ["pirate", "ship", "classic"],
    includes: ["Hull structure", "3 masts with sails", "Cannon deck", "Captain's quarters"],
  },
  {
    name: "Space Shuttle",
    description: "A detailed space shuttle with opening cargo bay and robotic arm.",
    category: "space",
    difficulty: "medium",
    emoji: "🚀",
    color: "#1ABC9C",
    brickCount: 1800,
    estimatedTime: 120,
    popularity: 4.7,
    downloads: 18234,
    featured: true,
    tags: ["space", "nasa", "shuttle"],
    includes: ["Main orbiter", "External tank", "Solid boosters", "Payload bay"],
  },
  {
    name: "Medieval Watchtower",
    description: "A fortified stone watchtower perfect for castle builds or standalone display.",
    category: "castle",
    difficulty: "easy",
    emoji: "🗼",
    color: "#7F8C8D",
    brickCount: 600,
    estimatedTime: 45,
    popularity: 4.5,
    downloads: 34567,
    featured: false,
    tags: ["castle", "medieval", "tower"],
    includes: ["Stone base", "Spiral staircase", "Lookout platform", "Flag pole"],
  },
  {
    name: "Sports Car",
    description: "A sleek sports car with opening doors, detailed engine, and working steering.",
    category: "vehicle",
    difficulty: "medium",
    emoji: "🏎️",
    color: "#E74C3C",
    brickCount: 1400,
    estimatedTime: 100,
    popularity: 4.6,
    downloads: 28901,
    featured: true,
    tags: ["car", "sports", "technic"],
    includes: ["Chassis", "Body panels", "Engine block", "Interior details"],
  },
  {
    name: "Treehouse Village",
    description: "An interconnected treehouse village with bridges, platforms, and nature details.",
    category: "fantasy",
    difficulty: "hard",
    emoji: "🌳",
    color: "#27AE60",
    brickCount: 2200,
    estimatedTime: 150,
    popularity: 4.8,
    downloads: 15678,
    featured: false,
    tags: ["nature", "village", "fantasy"],
    includes: ["3 tree structures", "Rope bridges", "Elevator system", "Ground details"],
  },
  {
    name: "Robot Mech",
    description: "A poseable giant robot mech with articulated limbs and weapon systems.",
    category: "mech",
    difficulty: "expert",
    emoji: "🤖",
    color: "#9B59B6",
    brickCount: 3200,
    estimatedTime: 200,
    popularity: 4.9,
    downloads: 21345,
    featured: true,
    tags: ["mech", "robot", "technic"],
    includes: ["Torso frame", "Articulated limbs", "Cockpit", "Weapon attachments"],
  },
  {
    name: "Cozy Cottage",
    description: "A charming countryside cottage with garden, chimney, and interior details.",
    category: "architecture",
    difficulty: "easy",
    emoji: "🏡",
    color: "#F39C12",
    brickCount: 800,
    estimatedTime: 60,
    popularity: 4.4,
    downloads: 45678,
    featured: false,
    tags: ["house", "cozy", "garden"],
    includes: ["Main structure", "Roof with chimney", "Garden elements", "Furniture set"],
  },
  {
    name: "Dragon",
    description: "A majestic dragon with poseable wings, tail, and opening jaw.",
    category: "creature",
    difficulty: "hard",
    emoji: "🐉",
    color: "#C0392B",
    brickCount: 2500,
    estimatedTime: 160,
    popularity: 4.9,
    downloads: 32109,
    featured: true,
    tags: ["dragon", "fantasy", "creature"],
    includes: ["Body structure", "Wing frames", "Articulated neck", "Flame effect pieces"],
  },
  {
    name: "Lunar Rover",
    description: "A detailed lunar exploration vehicle with scientific equipment and astronaut.",
    category: "space",
    difficulty: "easy",
    emoji: "🌙",
    color: "#BDC3C7",
    brickCount: 500,
    estimatedTime: 35,
    popularity: 4.3,
    downloads: 19876,
    featured: false,
    tags: ["space", "moon", "rover"],
    includes: ["Rover chassis", "Solar panels", "Antenna array", "Sample collector"],
  },
  {
    name: "Samurai Castle",
    description: "A traditional Japanese castle with multiple tiers, gates, and defensive walls.",
    category: "architecture",
    difficulty: "expert",
    emoji: "🏯",
    color: "#2C3E50",
    brickCount: 4000,
    estimatedTime: 240,
    popularity: 4.8,
    downloads: 11234,
    featured: true,
    tags: ["japanese", "castle", "architecture"],
    includes: ["Main keep", "Outer walls", "Gate house", "Garden courtyard"],
  },
  {
    name: "Submarine",
    description: "A detailed submarine with transparent observation dome and interior compartments.",
    category: "vehicle",
    difficulty: "medium",
    emoji: "🚢",
    color: "#16A085",
    brickCount: 1600,
    estimatedTime: 110,
    popularity: 4.5,
    downloads: 14567,
    featured: false,
    tags: ["submarine", "underwater", "vehicle"],
    includes: ["Hull sections", "Conning tower", "Propeller assembly", "Interior details"],
  },
];

// Complex LEGO Builds for Live Showcase
export const SHOWCASE_BUILDS = [
  {
    name: "Millennium Falcon",
    description: "The iconic Star Wars spacecraft in incredible detail",
    brickCount: 7541,
    complexity: "legendary",
    emoji: "🛸",
    color: "#7F8C8D",
    estimatedBuildTime: 480,
    features: [
      "Opening cockpit with detailed interior",
      "Rotating radar dish",
      "Landing gear mechanism",
      "Hidden compartments",
      "Minifigure scale interior"
    ],
  },
  {
    name: "Hogwarts Castle",
    description: "The complete wizarding school with all towers and grounds",
    brickCount: 6020,
    complexity: "legendary",
    emoji: "🏰",
    color: "#8E44AD",
    estimatedBuildTime: 420,
    features: [
      "Great Hall with floating candles",
      "Moving staircases",
      "Astronomy tower",
      "Whomping Willow",
      "Chamber of Secrets entrance"
    ],
  },
  {
    name: "Titanic",
    description: "The legendary ocean liner in stunning 1:200 scale",
    brickCount: 9090,
    complexity: "legendary",
    emoji: "🚢",
    color: "#2C3E50",
    estimatedBuildTime: 540,
    features: [
      "Split hull design",
      "Detailed deck structures",
      "Working propellers",
      "Interior cross-section",
      "Lifeboat davits"
    ],
  },
  {
    name: "Colosseum",
    description: "Ancient Rome's iconic amphitheater in full glory",
    brickCount: 9036,
    complexity: "legendary",
    emoji: "🏛️",
    color: "#D4A574",
    estimatedBuildTime: 500,
    features: [
      "Accurate architectural details",
      "Multiple seating tiers",
      "Underground hypogeum",
      "Partial reconstruction view",
      "Arena floor details"
    ],
  },
  {
    name: "AT-AT Walker",
    description: "The Imperial All Terrain Armored Transport",
    brickCount: 6785,
    complexity: "expert",
    emoji: "🤖",
    color: "#95A5A6",
    estimatedBuildTime: 380,
    features: [
      "Poseable legs",
      "Opening cockpit",
      "Troop deployment hatch",
      "Chin-mounted cannons",
      "Detailed interior"
    ],
  },
  {
    name: "Eiffel Tower",
    description: "Paris's iconic landmark at impressive scale",
    brickCount: 10001,
    complexity: "expert",
    emoji: "🗼",
    color: "#5D4E37",
    estimatedBuildTime: 450,
    features: [
      "Accurate lattice structure",
      "Three observation decks",
      "Elevator mechanism",
      "Night lighting system",
      "Detailed base plaza"
    ],
  },
  {
    name: "Batmobile Tumbler",
    description: "The Dark Knight's tactical assault vehicle",
    brickCount: 2049,
    complexity: "hard",
    emoji: "🦇",
    color: "#1A1A1A",
    estimatedBuildTime: 180,
    features: [
      "Opening cockpit",
      "Ejectable Batpod",
      "Stealth mode panels",
      "Working suspension",
      "Weapon systems"
    ],
  },
  {
    name: "Taj Mahal",
    description: "India's monument to eternal love",
    brickCount: 5923,
    complexity: "expert",
    emoji: "🕌",
    color: "#FDFEFE",
    estimatedBuildTime: 360,
    features: [
      "Intricate dome details",
      "Four minarets",
      "Reflecting pool",
      "Garden pathways",
      "Interior chamber"
    ],
  },
  {
    name: "Saturn V Rocket",
    description: "NASA's legendary Moon rocket",
    brickCount: 1969,
    complexity: "medium",
    emoji: "🚀",
    color: "#ECF0F1",
    estimatedBuildTime: 150,
    features: [
      "Separable stages",
      "Lunar module",
      "Command module",
      "Display stand",
      "Accurate markings"
    ],
  },
  {
    name: "Great Wall of China",
    description: "A section of the ancient wonder with watchtowers",
    brickCount: 3456,
    complexity: "hard",
    emoji: "🧱",
    color: "#7F8C8D",
    estimatedBuildTime: 240,
    features: [
      "Multiple wall sections",
      "Guard towers",
      "Mountain terrain",
      "Defensive features",
      "Minifigure soldiers"
    ],
  },
];

export default {
  FEATURED_AGENTS,
  COMMUNITY_CHALLENGES,
  BUILD_TEMPLATES,
  SHOWCASE_BUILDS,
};
